### ISSUE TITLE
[POST] - /api/map/address 400

### ISSUE THREAD

**Issue by TheOrionsB** [ARKultur/naboo#20]
<img width="1588" alt="Screenshot 2021-12-13 at 16 49 46" src="https://user-images.githubusercontent.com/44578736/145843786-58d64ed0-7593-47fe-8caa-ea0ad185fc5d.png">

lol /api/maps/address [POST] no work

**Comment by bogdzn** [comment]
![example](https://user-images.githubusercontent.com/29751352/146024897-aca13d41-83a0-49c5-9c42-1b8d685dd2af.png)

should be formatted like this
