### ISSUE TITLE
Deploy to DockerHub when releasing version

### ISSUE THREAD

**Issue by djnnvx** [ARKultur/naboo#24]
- a successful push to `dev` should do : 
```bash
docker tag naboo:${VERSION}-dev bogdzn/naboo:${VERSION}-dev
docker push bogdzn/naboo:${VERSION}-dev
```
- a successful push to `canon` should do :
```bash
docker tag naboo:${VERSION}-dev bogdzn/naboo:${VERSION}
docker push bogdzn/naboo:${VERSION}
```

we will of course have to properly manage docker credentials

**Comment by SheItoon** [comment]
- [ ] Store credentials somewhere
- [ ] only triggers if the other CI succeeded
- [ ] push the docker image with the correct tags as initially asked
